export const DEPOSIT_WITHDRAW_AMOUNT = 100;
export const BUY_SELL_BITCOIN_AMOUNT = 1;
export const INC_DEC_BITCOIN_PRICE = 1000;

export const DEPOSIT_REQUEST = 'DEPOSIT_REQUEST';
export const WITHDRAW_REQUEST = 'WITHDRAW_REQUEST';
export const BUY_BITCOIN_REQUEST = 'BUY_BITCOIN_REQUEST';
export const SELL_BITCOIN_REQUEST = 'SELL_BITCOIN_REQUEST';
export const INC_BITCOIN_REQUEST = 'INC_BITCOIN_REQUEST';
export const DEC_BITCOIN_REQUEST = 'DEC_BITCOIN_REQUEST';

export const LOCALSTORAGE_BALANCE_KEY = 'BALANCE';
export const LOCALSTORAGE_HISTORY_KEY = 'HISTORY';
